import type { Metadata } from "next";
import Image from 'next/image'
import Logo from "../public/img/logo.svg";
import { Inter } from "next/font/google";
import "./globals.css";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${inter.className}, h-screen mb-auto`}>
        {children}
        <div className="flex flex-row justify-center sm:mx-auto lg:w-1/3">
          <div className="basis-1/2">
            <Image
              className="basis-1/2 relative bottom-2 mr-8 mx-auto h-10 w-40"
              src={Logo}
              alt="Your Company"
            />
          </div>
          <div className="absolute left-1/2 w-0.5 bg-slate-300 h-7"></div>
          <div className="basis-1/2">
            <span className="basis-1/2 text-xs ml-5 text-[#C0CCDA]"> © 2022 Bitnovo. All rights reserved.</span>
          </div>
        </div>
      </body>
    </html>
  );
}
